#!/bin/sh
# Asterisk entrypoint — auto-detects host IP and container subnet for NAT/RTP config.
# Generates /etc/asterisk/pjsip_transport.conf before starting Asterisk.

set -e

# Use EXTERNAL_IP if provided, otherwise detect.
NAT_IP="${EXTERNAL_IP:-}"

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(getent ahostsv4 host.docker.internal 2>/dev/null | head -1 | awk '{print $1}')
fi

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(ip route 2>/dev/null | grep default | awk '{print $3}')
fi

if [ -z "$NAT_IP" ]; then
  echo "WARNING: Could not detect host IP. SIP NAT/RTP may not work."
  NAT_IP="0.0.0.0"
fi

# Detect container's own IP and derive its /24 subnet for local_net.
# This prevents the host's IP from matching local_net, which would cause
# Asterisk to skip external_media_address for host-originated traffic.
CONTAINER_IP=$(hostname -i 2>/dev/null | awk '{print $1}')
if [ -n "$CONTAINER_IP" ]; then
  CONTAINER_SUBNET=$(echo "$CONTAINER_IP" | awk -F. '{printf "%s.%s.%s.0/24", $1, $2, $3}')
else
  # Fallback: broad RFC1918 ranges (may cause issues on some networks)
  CONTAINER_SUBNET="10.0.0.0/8"
fi

echo "xphone-test Asterisk: NAT_IP=$NAT_IP CONTAINER_SUBNET=$CONTAINER_SUBNET"

cat > /etc/asterisk/pjsip_transport.conf << EOF
; Auto-generated by entrypoint.sh
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=$NAT_IP
external_signaling_address=$NAT_IP
local_net=$CONTAINER_SUBNET
local_net=127.0.0.0/8
EOF

exec /usr/sbin/asterisk "$@"
