#!/bin/sh
# Asterisk entrypoint — auto-detects host IP for NAT/RTP config.
# Generates /etc/asterisk/pjsip_transport.conf before starting Asterisk.

set -e

# Use EXTERNAL_IP if provided, otherwise detect.
NAT_IP="${EXTERNAL_IP:-}"

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(getent ahostsv4 host.docker.internal 2>/dev/null | head -1 | awk '{print $1}')
fi

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(ip route 2>/dev/null | grep default | awk '{print $3}')
fi

if [ -z "$NAT_IP" ]; then
  echo "WARNING: Could not detect host IP. SIP NAT/RTP may not work."
  NAT_IP="0.0.0.0"
fi

echo "xphone-test Asterisk: external_media_address=$NAT_IP"

cat > /etc/asterisk/pjsip_transport.conf << EOF
; Auto-generated by entrypoint.sh
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=$NAT_IP
external_signaling_address=$NAT_IP
local_net=172.16.0.0/12
local_net=10.0.0.0/8
local_net=192.168.0.0/16
local_net=100.64.0.0/10
EOF

exec /usr/sbin/asterisk "$@"
